#pragma once

#include "d1_Captcha.h"
#include "d2_Checksum.h"
#include "d3_SpiralMemory.h"
#include "d4_Passphrase.h"
#include "d5_Trampoline.h"
#include "d6_Realloc.h"
#include "d7_Circus.h"
#include "d8_Registers.h"
#include "d9_Streams.h"
#include "d10_KnotHash.h"
#include "d11_HexGrid.h"
#include "d12_PipeMessage.h"
#include "d13_Firewall.h"
#include "d14_Defrag.h"
#include "d15_Generators.h"
#include "d16_Dance.h"
//where is d17?
#include "d18_Duet.h"
#include "d19_Routing.h"
#include "d20_ParticleSwarm.h"
#include "d21_FractalArt.h"
#include "d22_Infecting.h"
#include "d23_Coprocessor.h"
#include "d24_Bridge.h"
#include "d25_TuringMachine.h"